# Generated by Django 4.2.25 on 2025-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeepfakeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.CharField(
                        help_text="Short description of the scenario shown to the player.",
                        max_length=255,
                    ),
                ),
                (
                    "real_image_path",
                    models.CharField(
                        help_text="Filesystem or CDN path to the authentic image.",
                        max_length=512,
                    ),
                ),
                (
                    "fake_image_path",
                    models.CharField(
                        help_text="Filesystem or CDN path to the AI-generated counterfeit image.",
                        max_length=512,
                    ),
                ),
                (
                    "key_flaw",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of the critical flaw that reveals the fake image.",
                    ),
                ),
                (
                    "technique_tip",
                    models.TextField(
                        help_text="One-sentence technique that helps players identify deepfakes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
