# Generated by Django 4.2.25 on 2025-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short name or identifier for the scenario presented to the player.",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="AI generated content that needs to be reviewed for compliance."
                    ),
                ),
                (
                    "risk_label",
                    models.CharField(
                        choices=[
                            ("compliant", "内容合规"),
                            ("non_compliant", "内容不合规"),
                            ("data_leak", "客户数据泄露"),
                            ("misinformation", "虚假信息"),
                        ],
                        help_text="Expected classification of the risk contained in the content.",
                        max_length=32,
                    ),
                ),
                (
                    "analysis",
                    models.TextField(
                        help_text="Explanation shown after answering that highlights the risk signals."
                    ),
                ),
                (
                    "technique_tip",
                    models.TextField(
                        help_text="Actionable tip that helps players identify similar compliance risks."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
