"""
Django settings for games_backend project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse, unquote
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_ENV_CACHE = None


def _load_env_config():
    conf_path = BASE_DIR / ".env"
    if not conf_path.exists():
        raise ImproperlyConfigured("Missing .env. Please create it with required entries.")
    data = {}
    try:
        for raw in conf_path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            data[key.strip()] = value.strip().strip('"').strip("'")
    except Exception as exc:
        raise ImproperlyConfigured(f"Failed to read .env: {exc}") from exc
    return data


def _get_env_setting(key, default=None, *, required=False):
    global _ENV_CACHE
    if _ENV_CACHE is None:
        _ENV_CACHE = _load_env_config()
    value = _ENV_CACHE.get(key)
    if value is None or value == "":
        value = default
    if required and (value is None or value == ""):
        raise ImproperlyConfigured(f"{key} not configured in .env")
    return value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=g8#9=w(1@^wu(y_f*0g_dabi26kq9xrqtq39#*r$zzmyw++h@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


def _csv_list_setting(key, default=""):
    value = _get_env_setting(key, default)
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


_DEFAULT_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5000",
    "http://localhost:5000",
    "http://127.0.0.1:5001",
    "http://localhost:5001",
    "http://150.223.58.162:5001",
]

CSRF_TRUSTED_ORIGINS = sorted(
    set(_DEFAULT_TRUSTED_ORIGINS) | set(_csv_list_setting("CSRF_TRUSTED_ORIGINS", ""))
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "deepfake",
    "riskhunter",
    "mbtispy",
    "prize",
    "mbtitest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "games_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "games_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _db_from_config():
    """Return DATABASES['default'] from a config file that defines DATABASE_URL.

    Config file path: BASE_DIR / '.env'
    Format: a single line like `DATABASE_URL=postgres://user:pass@host:5432/dbname`

    Raises ImproperlyConfigured if file missing or DATABASE_URL not set.
    """

    database_url = _get_env_setting("DATABASE_URL", required=True)

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    engine_map = {
        "postgres": "django.db.backends.postgresql",
        "postgresql": "django.db.backends.postgresql",
        "postgis": "django.db.backends.postgresql",
        "mysql": "django.db.backends.mysql",
        "mariadb": "django.db.backends.mysql",
        "sqlite": "django.db.backends.sqlite3",
        "sqlite3": "django.db.backends.sqlite3",
    }

    engine = engine_map.get(scheme)
    if not engine:
        raise ImproperlyConfigured(f"Unsupported DATABASE_URL scheme: {scheme}")

    if engine.endswith("sqlite3"):
        # For sqlite, path may be like sqlite:///path/to/db.sqlite3 or sqlite://:memory:
        path = parsed.path or ""
        if path.startswith("/"):
            name = unquote(path)
        else:
            name = ":memory:" if path == ":memory:" else str(BASE_DIR / "db.sqlite3")
        return {"ENGINE": engine, "NAME": name}

    return {
        "ENGINE": engine,
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }

    # unreachable
    raise ImproperlyConfigured("DATABASE_URL parsing failed")


DATABASES = {"default": _db_from_config()}

# Fail fast if database is unreachable
def _ensure_db_connection():
    from django.db import connections
    try:
        conn = connections["default"]
        conn.ensure_connection()
    except Exception as exc:  # django.db.utils.OperationalError and others
        raise ImproperlyConfigured(f"Database connection failed: {exc}") from exc

_ensure_db_connection()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "Resources",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis configuration for game caches
REDIS_URL = _get_env_setting("REDIS_URL", default="redis://127.0.0.1:6379/0")
try:
    MBTISPY_SESSION_TTL = int(_get_env_setting("MBTISPY_SESSION_TTL", default="7200"))
except (TypeError, ValueError) as exc:
    raise ImproperlyConfigured("MBTISPY_SESSION_TTL must be an integer.") from exc
MBTISPY_SESSION_PREFIX = _get_env_setting("MBTISPY_SESSION_PREFIX", default="mbtispy:session:")
MBTISPY_SESSION_LOCK_PREFIX = _get_env_setting("MBTISPY_SESSION_LOCK_PREFIX", default="mbtispy:lock:")
try:
    MBTISPY_LOCK_TIMEOUT = int(_get_env_setting("MBTISPY_LOCK_TIMEOUT", default="5"))
    MBTISPY_LOCK_WAIT = int(_get_env_setting("MBTISPY_LOCK_WAIT", default="5"))
except (TypeError, ValueError) as exc:
    raise ImproperlyConfigured("MBTISPY lock settings must be integers.") from exc
LLM_BASE_URL = _get_env_setting("LLM_BASE_URL", default="https://api.deepseek.com")
LLM_API_KEY = _get_env_setting("LLM_API_KEY", default="")
LLM_MODEL = _get_env_setting("LLM_MODEL", default="deepseek-chat")
